alias brightness="brightnessctl set 50%"
alias c="clear"
alias cp="cp -ip"
alias diff="diff --color=auto"
alias e="nvim +TSUpdate"
alias find="fd --hidden"
alias grep="rg -i"
alias ka="killall"
alias ls="eza --icons --group-directories-first --no-permissions --no-user --git -lao"
alias mv="mv -i"
alias n='nnn -deHu "$(fzf)"'
alias pkg="makepkg -cirs"
alias rm="rm -i"
alias sudo="doas"
alias venv="python -m venv venv && source venv/bin/activate"
alias vite="npm create vite@latest . -- --template react && npm install"
alias yd="yt-dlp"

alias install="sudo pacman -S"
alias orphan="pacman -Qdtq"
alias package="pacman -Qq | grep"
alias packlist="pacman -Qq | wc -l"
alias remove="sudo pacman -Rcnus"
alias search="pacman -Ss"
alias update="sudo pacman -Syu"

alias ga="git add ."
alias gc="git clone"
alias gi="git init"
alias gl="git log"
alias gp="git pull"
alias gs="git status"

alias restart="sudo systemctl restart"
alias start="sudo systemctl start"
alias stop="sudo systemctl stop"
alias status="systemctl status"
alias enablen="sudo systemctl enable --now"
alias disablen="sudo systemctl disable --now"
